### ISSUE TITLE
DTU analysis run

### ISSUE THREAD

**Issue by Merlino-git** [berilerdogdu/SPIT#3]
Hey, it's me again. I tried to just run the analysis without the parameters fitting and got this error:

`spit dtu -i counts4SPIT.tsv -m tx2gene.tsv -l pheno.tsv --n_small 3 -O prova_SPIT/ --n_iter 100 --plot
`

Chewing in progress:
1 iterations completed.Traceback (most recent call last):
  File "/home/merlino/.local/bin/spit", line 8, in <module>
    sys.exit(main())
  File "/home/merlino/.local/lib/python3.10/site-packages/spit/run_spit.py", line 176, in main
    args.func(args)
  File "/home/merlino/.local/lib/python3.10/site-packages/spit/run_spit.py", line 50, in handle_dtu
    spit_test(args)
  File "/home/merlino/.local/lib/python3.10/site-packages/spit/spit_test.py", line 149, in main
    min_perm_p_arr, perm_p_medians = mannwhitneyu_permutation(IFs, samples, case_sample_size, args.n_iter, args.n_small)
  File "/home/merlino/.local/lib/python3.10/site-packages/spit/spit_test.py", line 105, in mannwhitneyu_permutation
    min_it_p_val = np.random.choice(np.sort(p_arr)[0:int(m_1.shape[1]*0.01)])
  File "mtrand.pyx", line 934, in numpy.random.mtrand.RandomState.choice
ValueError: 'a' cannot be empty unless no samples are taken

**Comment by berilerdogdu** [comment]
Hello!

Would you be able to share your input files with me so that I can replicate this error?

Thanks,
Beril

**Comment by Merlino-git** [comment]
Sure! Should I drop them here?

**Comment by berilerdogdu** [comment]
Sure, if they are not too large. You could also share them through Google drive.

**Comment by Merlino-git** [comment]
Sure, here you go the drive folder 

https://drive.google.com/drive/folders/1inBoRO59Lg4aFFXAJe2KD1Xi-kpwA5Rn?usp=sharing

**Comment by berilerdogdu** [comment]
Could you grant me access to the folder?

**Comment by berilerdogdu** [comment]
Hello! Thank you very much for providing the data. I managed to reproduce the error you encountered. The issue stemmed from the labeling of control and case samples with strings ("ctrl" and "siHRNPNL") instead of 0s and 1s. Once this was fixed, the program ran smoothly without any problems. For more guidance on formatting your design/phenotype file, please refer to our Colab notebook tutorial. I hope this helps!

**Comment by Merlino-git** [comment]
Hey Beril, thanks for getting back to me. I just tried changing the "condition" column in the pheno.tsv file with 0s and 1s but unfortunately I got the very same error as before. Do I need to change something else?

**Comment by berilerdogdu** [comment]
Interesting, what was your filter command?

**Comment by Merlino-git** [comment]
I didn't filter thinking that I was already trying on a very small sample case and maybe filtering would be to strict for a 3v3 example. 
Is the filtering step necessary for the tool to work?

**Comment by berilerdogdu** [comment]
Hey! Yes, the "filter" module not only filters transcript counts but also computes isoform fraction values. This caused issues with subsequent SPIT modules. I realize the confusion the naming might cause and appreciate you flagging it. I've now renamed the module "preprocess" and updated our tutorial for clearer instructions on command order.

Additionally, there's a new option for running SPIT in "--no_clusters" mode, so that the users do not have to manually specify "--n_small" or "--bandwidth" in each command. With these updates, you can install the latest SPIT version and execute the following commands on your dataset:
```
spit preprocess -i counts4SPIT.tsv -m tx2gene.tsv -l pheno.tsv --no_clusters --keep_all_nonzeros
spit dtu -i counts4SPIT.tsv -m tx2gene.tsv -l pheno.tsv --no_clusters --plot
```

The commands ran smoothly on the input you provided from my end. However, if you encounter any further issues, please let me know. You might receive a warning regarding the p-value threshold exceeding 0.05. Typically, this might signal issues with the input data. However, given your sample sizes of 3 vs. 3, the lowest p-value achievable with a Mann-Whitney U test on such datasets is close to 0.1. Unless you acquire more data, you can disregard this warning.
